services:
  endpoint:
    container_name: image-API
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${ON_PORT}:${ON_PORT}"
    environment:
      - ENV=development
    restart: always
    networks:
      - request
    tty: true
    stdin_open: true

networks:
  request:
    external: true